spring.application.name=scheduleDemo-api-www

# Datasource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/schedule_demo?useSSL=false&serverTimezone=Asia/Taipei&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# SQL Initialization
spring.sql.init.mode=always

# Logging Configuration
logging.level.com.example.scheduledemo=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# swagger
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
knife4j.enable=true

springdoc.packagesToScan=com.web.cc.scheduleDemo.api.rest
springdoc.group-configs[0].paths-to-match=/**
springdoc.group-configs[0].group=com.web.cc.scheduleDemo.api.rest